baseURL = 'https://blog.orderify.kr'
languageCode = 'ko-kr'
title = 'Orderify'
theme = "paper"

[params]
    avatar = 'https://blog.orderify.kr/LOGO.png'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
    name = 'Orderify' # Name of the author
    bio = 'SW마에스트로 Orderify 팀 블로그입니다.'

